version: '3.8'
services:
  api:
    build: .
    container_name: auth-client-frontend
    ports:
      - '2021:3000'
    volumes:
      - /app
      - /app/node_modules
    stdin_open: true
    tty: true