version: '3.8'
services:
  web:
    build: .
    container_name: server-web-auth
    command: yarn dev
    volumes:
      - /app
      - /app/node_modules
    ports:
      - "3021:4021"
        # MongoDB services
  mongo_db:
    container_name: mongodb-auth
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    container_name: server-api-auth
    ports:
      - "4021:3021"
    environment:
      PORT: 3021
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: authDB
      NAME: Aleksandr
    depends_on:
      - mongo_db  
    volumes:
      - /app
      - /app/node_modules
volumes:
  mongo_db: {}